version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      custom_network:
        ipv4_address: 192.168.0.10
  networks:
    custom_network:
      driver: bridge
      ipam:
        config:
          - subnet:192.168.0.0/24
            gateway:192.168.0.1
          
